version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  build:
    working_directory: ~/angular-front-personas
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-front-personas-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: angular-front-personas-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test
      - run: npm run lint
      - run: npm run build
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
